### ISSUE TITLE
Ash Wed collect special case

### ISSUE THREAD

**Issue by toddfoster** [gbj/commonprayer#2]
On Ash Wednesday, the collect displays twice:
https://www.commonprayeronline.org/en/daily-readings/2022-03-02

Feels like an off by one error. 

I'll also note with amusement that I started to file an issue about the Ash Wed collect run amok! A project like this, it seems, is likely to attract "issues" that are not about your code, but about interpretation of the tradition. Case in point:

The Ash Wed collect continues throughout Lent in commonprayeronline/daily-readings. I thought this might be a bug. I see a rubric about this on BCP 217, but it seems ambiguous. Checking Hatchett, this ambiguity seems frustratingly purposeful: the 1928 BCP specified until Palm Sunday. But the earliest use of the the rubric (in 1892, following Scottish 1637) was only meant to cover the Thurs/Fri/Sat following Ash Wed. Why did the 1979 book refrain from being clear on this issue?

**Comment by gbj** [comment]
Thanks, Todd.

In terms of logic it's displaying once as the Collect of the Day, and once as the seasonal collect for Lent. The collects should be deduplicated, I've probably just messed that process up.

I agree with your sense that a plain reading of the 1979 BCP does _not_ support the traditions of using the collects for Ash Wednesday and for the First Sunday of Advent as "seasonal collects" repeated on every day of those seasons, but know that I receive requests for them all the time! The rubrics in the 1962 Canadian BCP (which is the other one with which I'm very familiar) is much more helpful: _This Collect is to be repeated every day after the other Collects in Advent, until Christmas Eve._ and _This Collect is to be read every day in Lent after the Collect appointed for the day until Holy Week._ These are virtually identical to the 1662 rubrics, which suggests it's another of our American departures from that tradition that has, perhaps, been re-imported (or simply persisted).
